/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cookies': typeof CookiesRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agb' | '/cookies' | '/datenschutz' | '/faq' | '/impressum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agb' | '/cookies' | '/datenschutz' | '/faq' | '/impressum'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/cookies'
    | '/datenschutz'
    | '/faq'
    | '/impressum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  CookiesRoute: typeof CookiesRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FaqRoute: typeof FaqRoute
  ImpressumRoute: typeof ImpressumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  CookiesRoute: CookiesRoute,
  DatenschutzRoute: DatenschutzRoute,
  FaqRoute: FaqRoute,
  ImpressumRoute: ImpressumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
